### ISSUE TITLE
Error generating code for schema with unions

### ISSUE THREAD

**Issue by sav007** [Shopify/graphql_java_gen#9]
Tried to run generation tool against Github Schema got next message:

```
graphql_schema.rb:203:in `fields': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from .../templates/APISchema.java.erb:85:in `block in generate'
	from .../templates/APISchema.java.erb:68:in `each'
	from .../templates/APISchema.java.erb:68:in `generate'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/erb.rb:864:in `result'
	from .../lib/graphql_java_gen.rb:31:in `generate'
	from.../graphql_java_gen.rb:27:in `save'
```

The error doesn't tell what type caused the issue.

**Comment by dylanahsmith** [comment]
Looks like it is a bug in how unions are generated.  That wasn't never tested well since we haven't used unions.
